In [1]:
import torch
import numpy as np
import torch.nn as nn
import torchvision
import torch.utils.data
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.optim as optim

## Array using Torch

In [4]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
torch.rand(2,2)

tensor([[0.4393, 0.8118],
        [0.1083, 0.5204]])

In [8]:
a = torch.rand(3,5)
print(a)
a.shape

tensor([[0.6451, 0.5495, 0.8725, 0.0698, 0.4518],
        [0.4758, 0.4186, 0.8639, 0.2717, 0.1211],
        [0.9148, 0.1816, 0.4429, 0.4627, 0.4286]])


torch.Size([3, 5])

## Array using Numpy

In [10]:
np.array([[7,8,9],[4,5,6]])

array([[7, 8, 9],
       [4, 5, 6]])

In [14]:
np.random.rand(3,5)

array([[0.92512687, 0.46447765, 0.22715422, 0.74111427, 0.53988287],
       [0.70356362, 0.65977961, 0.79985837, 0.941016  , 0.66739363],
       [0.65174978, 0.22927659, 0.03476242, 0.12687789, 0.17947045]])

In [2]:
a = torch.rand(2,2)
b = torch.rand(2,2)

## Multiplication and Addition

In [20]:
torch.matmul(a,b)

tensor([[0.7064, 0.6461],
        [0.2315, 0.2626]])

In [22]:
np.dot(a,b)

array([[0.7063823 , 0.6460733 ],
       [0.23150918, 0.26263553]], dtype=float32)

a* b and np.multiply are same 1st*1st 2nd*2nd

torch.matmul and np.dot are same which uses matrix multiplication

In [23]:
a*b

tensor([[0.6960, 0.0187],
        [0.0048, 0.2540]])

In [24]:
np.multiply(a,b)

tensor([[0.6960, 0.0187],
        [0.0048, 0.2540]])

In [5]:
print(a+b)
torch.add(a,b)

tensor([[0.6752, 0.8426],
        [0.6329, 0.8533]])


tensor([[0.6752, 0.8426],
        [0.6329, 0.8533]])

In [6]:
a.add(b)

tensor([[0.6752, 0.8426],
        [0.6329, 0.8533]])

### Uninitialized or Empty

In [32]:
e = torch.empty(4,4)
print(e)

tensor([[6.6123e-39, 7.6225e-39, 8.4490e-39, 1.0102e-38],
        [9.0919e-39, 1.0102e-38, 8.9082e-39, 8.4489e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39, 9.2755e-39]])


### Zeros and Ones

In [38]:
z = torch.zeros(4,3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [39]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
torch.zeros(3,3,dtype= torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [41]:
torch.ones(5,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [43]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Identity and Eye

In [47]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
e = torch.eye(3)
e

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Numpy array to torch_tensor

In [48]:
t = torch.from_numpy(i)
t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

In [50]:
#tensor to numpy array
e.numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

## Indexing and Slicing

In [7]:
mat = torch.rand(4,4)

In [8]:
mat

tensor([[0.2041, 0.8621, 0.9627, 0.1136],
        [0.3600, 0.0345, 0.0108, 0.5727],
        [0.0583, 0.4909, 0.0277, 0.8990],
        [0.4388, 0.5824, 0.9688, 0.4591]])

In [10]:
mat[:,1]

tensor([0.8621, 0.0345, 0.4909, 0.5824])

In [12]:
# will give valuse from standard normal distribution(- to +)
torch.randn(4,4)

tensor([[-0.3892,  1.1748, -1.1716, -1.5329],
        [-0.4552, -0.0256, -0.0788,  0.0546],
        [-1.0449, -1.5923,  1.0532, -0.8044],
        [ 0.4828, -0.1064,  0.6598,  1.2202]])

In [17]:
y1 = mat.view(16)
print(y1)
y2 = mat.view(-1,2)
print(y2)
y3 = mat.view(2,-1)
print(y3)

tensor([0.2041, 0.8621, 0.9627, 0.1136, 0.3600, 0.0345, 0.0108, 0.5727, 0.0583,
        0.4909, 0.0277, 0.8990, 0.4388, 0.5824, 0.9688, 0.4591])
tensor([[0.2041, 0.8621],
        [0.9627, 0.1136],
        [0.3600, 0.0345],
        [0.0108, 0.5727],
        [0.0583, 0.4909],
        [0.0277, 0.8990],
        [0.4388, 0.5824],
        [0.9688, 0.4591]])
tensor([[0.2041, 0.8621, 0.9627, 0.1136, 0.3600, 0.0345, 0.0108, 0.5727],
        [0.0583, 0.4909, 0.0277, 0.8990, 0.4388, 0.5824, 0.9688, 0.4591]])


## Forward Propagation

In [2]:
a = torch.tensor([2])
b = torch.tensor([-4])
c = torch.tensor([-2])
d = torch.tensor([2])

e = a+b
f = c*d

g = e*f
g

tensor([8])

## Backward Propagation

In [9]:
a = torch.tensor([3.],requires_grad=True)
b = torch.tensor([5.],requires_grad=True)
c = torch.tensor([2.],requires_grad=True)
d = torch.tensor([4.],requires_grad=True)

e = a+b
f = c*d

r = e *f

r.backward()
print(a.grad,b.grad,c.grad,d.grad)


tensor([8.]) tensor([8.]) tensor([32.]) tensor([16.])


## Fully connected NN

In [11]:
inp_layer = torch.rand(10)

w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(inp_layer,w1)
h2 = torch.matmul(h1,w2)

out_layer = torch.matmul(h2,w3)

print(h1)
print(h2)

print(out_layer)

tensor([3.0283, 1.7952, 2.2020, 1.9236, 2.5687, 2.7295, 1.8487, 2.2590, 3.3236,
        2.0414, 2.2264, 2.7946, 2.1390, 2.9071, 3.2669, 2.6007, 1.8940, 3.1074,
        2.9057, 3.1515])
tensor([27.1523, 24.7745, 18.7990, 25.4979, 22.4448, 23.3391, 18.8543, 17.9284,
        29.9506, 20.4610, 24.6769, 29.6728, 34.9653, 20.9734, 22.3888, 29.5052,
        28.8368, 28.6883, 28.4571, 27.1506])
tensor([254.0937, 284.9214, 241.5870, 264.5339])


## Building a NN

In [3]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,20)
        self.output = nn.Linear(20,4)
        
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.output(x)
        return x
    
    
input_layer = torch.rand(10)
net = Net()
res = net(input_layer)
res

tensor([ 0.0822, -0.0992, -0.1183,  0.2308], grad_fn=<AddBackward0>)

## Activation Function

In [41]:
il = torch.tensor([0.0401,-0.9005])

w1 = torch.tensor([[-0.1094,-0.8285],[0.3327,-0.0461]])

w2 = torch.tensor([[0.6856,-1.7650],[-0.1092,-0.1620]])

w3 = torch.tensor([[0.8824,0.1268],[-0.8753,-0.3277]])

h1 = torch.matmul(il,w1)
h2 = torch.matmul(h1,w2)

# using hidden layers
o = torch.matmul(h2,w3)
print(o)

# using weight composed
wc = torch.matmul(w1,w2)
fw = torch.matmul(wc,w3)
O = torch.matmul(il,fw)
print(O)

tensor([-0.6532, -0.2019])
tensor([-0.6532, -0.2019])


In [46]:
relu = nn.ReLU()

il = torch.tensor([0.0401,-0.9005])
w1 = torch.tensor([[-0.1094,-0.8285],[0.3327,-0.0461]])
w2 = torch.tensor([[0.6856,-1.7650],[-0.1092,-0.1620]])
w3 = torch.tensor([[0.8824,0.1268],[-0.8753,-0.3277]])

ah1 = relu(torch.matmul(il,w1))
ah2 = relu(torch.matmul(ah1,w2))

print(torch.matmul(ah2,w3))

wc = relu(torch.matmul(w1,w2))
fw = relu(torch.matmul(wc,w3))

print(torch.matmul(il,fw))


tensor([0., 0.])
tensor([-0.1852, -0.0266])


In [36]:
relu = nn.ReLU()

t1 = torch.tensor([2.,-4.])

print(relu(t1))

t2 = torch.tensor([[2.,-4.],[1.2,0.]])

print(relu(t2))

tensor([2., 0.])
tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])


## Cross Entropy

In [6]:
logits = torch.rand([1,1000])
ground_truth = torch.tensor([437])

cross_entropy = nn.CrossEntropyLoss()

loss = cross_entropy(logits,ground_truth)
loss

tensor(7.4271)

# Preparing Dataset in Pytorch

### CIFAR10 Data set

In [3]:
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.4914,0.48216,0.44653),
                                                     (0.24703,0.24349,0.26159))])

In [4]:
train = torchvision.datasets.CIFAR10(root='./data', train=True,download=True,transform= transform,)

Files already downloaded and verified


In [5]:
test = torchvision.datasets.CIFAR10(root='./data', train=False,download=True,transform= transform,)

Files already downloaded and verified


In [6]:
trainloader = torch.utils.data.DataLoader(train, batch_size=32, shuffle=True, num_workers=4)
testloader = torch.utils.data.DataLoader(test, batch_size=32, shuffle=False, num_workers=4)

In [7]:
print(trainloader.dataset.data.shape,testloader.dataset.data.shape)
print(trainloader.batch_size)
print(testloader.batch_size)

(50000, 32, 32, 3) (10000, 32, 32, 3)
32
32


## MNIST Dataset

In [10]:
transform = transforms.Compose([transforms.ToTensor(),
                               transforms.Normalize((0.1307),(0.3081))])

In [12]:
train = torchvision.datasets.MNIST(root='./data', train=True,download=True,transform= transform)
test = torchvision.datasets.MNIST(root='./data', train=False,download=True,transform= transform)

In [13]:
trainload = torch.utils.data.DataLoader(train, batch_size=32, shuffle=True,num_workers=0)
testload = torch.utils.data.DataLoader(test, batch_size=32, shuffle=False,num_workers=0)

In [20]:
print(trainload.dataset.data.shape)
print(testload.dataset.test_data.shape)

torch.Size([60000, 28, 28])
torch.Size([10000, 28, 28])


In [22]:
print(trainload.batch_size)
print(testload.batch_size)

32
32


## Creating Neural Network

#### CIFAR 10 consist of 10 classes with 32 *32 size and has 3 channels

In [17]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(32 * 32 * 3,500)
        self.fc2 = nn.Linear(500,10)
        # instantiate all 2 linear layers
        
        # use the instantiated layers and return x
        
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

## Training the Neural Network

 First we instantiate the Net, the loss(cross-entropy), and the optimizer(adam)
 
 Adam optimizer works very well and is a version of gradient descent
 
 Then we loop 10 times over the entire dataset. We use zero_grad() function in order to not accumulate gradients from previous iterations
 
 when using iterators, we need to keep track of the number of items in the iterator. This is achieved by an inbuilt method called enumerate()
 
 The forward step is done using net(inputs), giving the result (output)
 
 we compute the loss function in the next line, and then we compute the gradients using loss.backward()
 
 Finally, we change the weights using optimizer with optimizer.step() command
 
 The line inputs = inputs.view(-1, 32*32*3) simply puts all entries o the images into vectors
 

In [18]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr = 3e-4)

for epoch in range(10):
    for i,data in enumerate(trainloader,0):
        inputs, labels = data
        inputs = inputs.view(-1, 32*32*3)
        
        optimizer.zero_grad()
        
        outputs = net(inputs)
        loss = criterion(outputs,labels)
        loss.backward()
        optimizer.step()
        

In [19]:
correct, total = 0,0
predictions = []
net.eval()

for i, data in enumerate(testloader,0):
    inputs, labels = data
    inputs = inputs.view(-1, 32*32*3)
    
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data,1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('The testing set accuracy of the network is : %d %%' % (100 * correct/total))

The testing set accuracy of the network is : 52 %


# Convolutional Neural Networks

### OOP way

In [20]:
image = torch.rand(16,3,32,32)

conv_filter = torch.nn.Conv2d(in_channels=3,
                             out_channels=1,
                             kernel_size=5,
                             stride=1,
                             padding=0)

output_feature = conv_filter(image)
print(output_feature.shape)

torch.Size([16, 1, 28, 28])


## Functional way

In [21]:
image = torch.rand(16,3,32,32)

filt = torch.rand(1,3,5,5)

out_feat_F = F.conv2d(image,filt,stride=1,padding=0)

print(out_feat_F.shape)

torch.Size([16, 1, 28, 28])


## Pooling

In [7]:
im = torch.Tensor([[[[3,1,3,5],
                     [6,0,7,9],
                     [3,2,1,4],
                     [0,2,4,3]]]])

max_pool = torch.nn.MaxPool2d(2)

out_feature = max_pool(im)
print(out_feature)

tensor([[[[6., 9.],
          [3., 4.]]]])


In [9]:
# Functional way
im = torch.Tensor([[[[3,1,3,5],
                     [6,0,7,9],
                     [3,2,1,4],
                     [0,2,4,3]]]])
out_feature = F.max_pool2d(im,2)

print(out_feature)

tensor([[[[6., 9.],
          [3., 4.]]]])


# Building a CNN

In [2]:
class Net(nn.Module):
    def __init__(self, num_classes=10):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2,2)
        self.fc = nn.Linear(128 * 4 * 4,num_classes)
        
    def forwaeed(self,x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        
        x = x.view(-1,128 * 4 * 4)
        return self.fc(x)

### Optimizer and Loss Function

In [3]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(),lr=3e-4)

### Training a CNN

In [4]:
for epoch in range(10):
    for i,data in enumerate(trainloader,0):
        inputs,labels = data
        
        # zero the parameter gradients
        optimizer.zero_grad()
        
        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    print('Finished Training')

NameError: name 'trainloader' is not defined

### Evaluating the results

In [5]:
correct, total = 0,0
predictions = []
net.eval()
for i, data in enumerate(testloader, 0):
    inputs,labels = data
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data,1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('The testing set accuracy of the network is : %d %%' % (100 * correct/total))

NameError: name 'testloader' is not defined

## Sequential Module

In [10]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
        # Declare all the layers for feature extraction
        self.features = nn.Sequential(nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1),
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1),
                                      nn.MaxPool2d(2,2), nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, padding=1),
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=20, out_channels=40, kernel_size=3, padding=1),
                                      nn.MaxPool2d(2,2), nn.ReLU(inplace=True))
        
        self.classifier = nn.Sequential(nn.Linear(7*7*40,1024),
                                        nn.ReLU(inplace=True),
                                       nn.Linear(1024,2048),
                                        nn.ReLU(inplace=True),
                                       nn.Linear(2048,10))

In [11]:
def forward(self, x):
    x = self.features(x)
    
    x = x.view(-1 , 7*7*40)
    
    x = self.classifier(x)
    return x

### Validation Sets

In [12]:
indices = np.arange(60000)
np.random.shuffle(indices)

train_loader = torch.utils.data.DataLoader(torchvision.datasets.MNIST(root='./data', download=True, train=True,
                                                                     transform= transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307),(0.3081))])),
                                          batch_size=64, shuffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[:55000]))

val_loader = torch.utils.data.DataLoader(torchvision.datasets.MNIST(root='./data', download=True, train=True,
                                                                     transform= transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307),(0.3081))])),
                                          batch_size=64, shuffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[55000:]))

test_loader = torch.utils.data.DataLoader(torchvision.datasets.MNIST(root='./data', download=True, train=False,
                                                                     transform= transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307),(0.3081))])),
                                          batch_size=64, shuffle=False)

In [16]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        self.relu = nn.ReLU()
        
        self.pool = nn.MaxPool2d(2,2)
        
        self.fc = nn.Linear(7*7*10,10)
        
    def forward(self,x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 7*7*10)
        return self.fc(x)

In [19]:
# Training cnn

for epoch in range(10):
    for i,data in enumerate(trainloader,0):
        inputs,labels = data
        
        # zero the parameter gradients
        optimizer.zero_grad()
        
        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    print('Finished Training')

NameError: name 'trainloader' is not defined

### Evaluating the result

In [17]:
correct, total = 0,0
predictions = []
net.eval()
for i, data in enumerate(val_loader, 0):
    inputs,labels = data
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data,1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('The testing set accuracy of the network is : %d %%' % (100 * correct/total))

NotImplementedError: Module [Net] is missing the required "forward" function

In [18]:
correct, total = 0,0
predictions = []
net.eval()
for i, data in enumerate(testloader, 0):
    inputs,labels = data
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data,1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('The testing set accuracy of the network is : %d %%' % (100 * correct/total))

NameError: name 'testloader' is not defined